import { Header } from "../components/Header";
import { Footer } from "../components/Footer";

export default function DisclaimerPage() {
    return (
        <div className="min-h-screen flex flex-col bg-brand-floralWhite">
            <Header />
            <main className="flex-grow container mx-auto px-4 py-12">
                <div className="max-w-4xl mx-auto prose prose-lg">
                    <h1 className="text-4xl font-bold text-brand-licorice mb-8">Disclaimer</h1>
                    
                    <h2>Service Availability</h2>
                    <p>
                        CodeAIgent is currently in early access. Features, availability, and performance may vary during this phase.
                    </p>

                    <h2>Generated Code</h2>
                    <p>
                        While we strive for high-quality output, the code generated by our AI:
                    </p>
                    <ul>
                        <li>Should be reviewed by developers before production use</li>
                        <li>May require modifications to match specific requirements</li>
                        <li>Is provided &quot;as is&quot; without warranties</li>
                    </ul>

                    <h2>Trello Integration</h2>
                    <p>
                        Our integration with Trello is subject to their terms of service and API limitations. We are not affiliated with or endorsed by Trello.
                    </p>

                    <h2>Intellectual Property</h2>
                    <p>
                        You retain all rights to your code and Trello data. The AI-generated code is provided under MIT license unless specified otherwise.
                    </p>

                    <h2>Limitation of Liability</h2>
                    <p>
                        CodeAIgent is not liable for any damages or losses arising from:
                    </p>
                    <ul>
                        <li>Use or inability to use the service</li>
                        <li>Generated code implementation</li>
                        <li>Service interruptions or data loss</li>
                    </ul>

                    <h2>Changes to Service</h2>
                    <p>
                        We reserve the right to modify, suspend, or discontinue any part of the service without prior notice.
                    </p>

                    <h2>Contact</h2>
                    <p>
                        For questions about this disclaimer, reach out through our social media channels.
                    </p>
                </div>
            </main>
            <Footer />
        </div>
    );
} 